# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='font',
            field=models.CharField(choices=[('comic', 'Comic'), ('grunge', 'Grunge'), ('pixel', 'Pixel'), ('sans', 'Sans'), ('script', 'Script'), ('serif', 'Serif'), ('slab', 'Slab')], default='sans', max_length=100),
        ),
        migrations.AlterField(
            model_name='last',
            name='font',
            field=models.CharField(choices=[('comic', 'Comic'), ('grunge', 'Grunge'), ('pixel', 'Pixel'), ('sans', 'Sans'), ('script', 'Script'), ('serif', 'Serif'), ('slab', 'Slab')], default='sans', max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='font',
            field=models.CharField(choices=[('comic', 'Comic'), ('grunge', 'Grunge'), ('pixel', 'Pixel'), ('sans', 'Sans'), ('script', 'Script'), ('serif', 'Serif'), ('slab', 'Slab')], default='sans', max_length=100),
        ),
    ]
